### ISSUE TITLE
Exported icons are sometimes 31x32 or 32x31 pixels

### ISSUE THREAD

**Issue by Faalagorn** [timbaker/tiled#6]
Not sure if it's a game bug or TileZed bug, but it seems that some item icons are sometimes exported as 31x32 px or 32x31 px instead of 32x32 px. The actual item is not cut off, but all other items are 32x32 with transparent background around.

I noticed that when uploading the newest icons from 41.78.16 to the PZwiki and documented it [on PZwiki](https://pzwiki.net/wiki/PZwiki:Style_guide#File_dimensions).

When I uploaded newest icons, I also noticed that while still 32x32, the previous icons were sometimes off by one pixel here and there. Is it because the TileZed change or some change in the game files?

E.g. https://pzwiki.net/wiki/File:BowlFull.png

https://pzwiki.net/w/images/archive/9/90/20230223004516%21BowlFull.png
https://pzwiki.net/w/images/9/90/BowlFull.png
(the icon is now moved 1 pixel down)

I wanted to test that with the newest version of the TileZed, but due to #5 I can't get it to working sadly, so I used the Windows version that is provided with the [Project Zomboid Modding Tools](https://steamdb.info/app/380880/depots/) on Steam.

**Comment by timbaker** [comment]
I checked Item_AliceBag.png, Item_DrawStringBag.png and Item_HelmetCrash.png.  The original files aren't 32x32 pixels.

**Comment by Faalagorn** [comment]
> I checked Item_AliceBag.png, Item_DrawStringBag.png and Item_HelmetCrash.png. The original files aren't 32x32 pixels.

Thanks! So that means it's the “issue” in the original tileset files in the game? It's so minor that no one probably noticed until then, but maybe something worth mentioning to the dev team? Or maybe it was already noticed and will fix itself in the upcoming updates?

I remember a similar issue about red pixels appearing in the tilesets that were eventually fixed in subsequent updates back before b41 :P 

BTW, I guess I could look into the code deeper, but where are these sizes stored in-game?

**Comment by timbaker** [comment]
The original image files are not 32x32.  Item icons are all individual images, not tilesets.
The original image sizes are stored in the .pack file.
